import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.signin': 'Sign In',
    'nav.getstarted': 'Get Started',
    'hero.title': 'Your Business, Powered by',
    'hero.title.highlight': 'AI Agents',
    'hero.subtitle': 'Deploy intelligent AI agents to automate sales, support, marketing, HR, and more. Scale your business without scaling your team.',
    'hero.cta.start': 'Get Started Free',
    'hero.cta.pricing': 'View Pricing',
    'features.title': 'AI Agents for Every Business Function',
    'features.subtitle': 'Deploy specialized agents that work 24/7 to grow your business',
    'feature.support.title': 'AI Customer Support',
    'onboarding.welcome': 'Welcome! Let\'s Set Up Your Company',
    'onboarding.setup': 'Company Settings',
    'onboarding.step1': 'Tell us about your company to get started',
    'onboarding.step2': 'Configure your company preferences',
    'onboarding.complete': 'Complete Setup',
    'company.nameplaceholder': 'Enter your company name',
    'feature.support.desc': 'Handle customer inquiries 24/7 with intelligent AI agents that resolve issues instantly',
    'feature.sales.title': 'Sales Agent',
    'feature.sales.desc': 'Qualify leads, schedule demos, and close deals automatically with AI-powered sales automation',
    'feature.marketing.title': 'Marketing Agent',
    'feature.marketing.desc': 'Create campaigns, analyze performance, and engage customers with data-driven marketing AI',
    'feature.hr.title': 'HR Agent',
    'feature.hr.desc': 'Streamline recruitment, onboarding, and employee queries with intelligent HR automation',
    'feature.accounting.title': 'Accounting Agent',
    'feature.accounting.desc': 'Process invoices, track expenses, and generate financial reports automatically',
    'feature.analytics.title': 'Data Analysis Agent',
    'feature.analytics.desc': 'Analyze data, generate insights, and create visualizations with AI-powered analytics',
    'testimonials.title': 'Trusted by Forward-Thinking Companies',
    'testimonials.subtitle': 'See what our customers have to say about AI Agents',
    'cta.title': 'Ready to Transform Your Business?',
    'cta.subtitle': 'Join thousands of companies using AI agents to automate their operations',
    'cta.button': 'Start Your Free Trial',
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.contact': 'Contact',
    'footer.features': 'Features',
    'footer.pricing': 'Pricing',
    'footer.usecases': 'Use Cases',
    'footer.about': 'About',
    'footer.blog': 'Blog',
    'footer.careers': 'Careers',
    'footer.rights': 'All rights reserved',
    'auth.welcome': 'Welcome Back',
    'auth.getstarted': 'Get Started',
    'auth.signin.subtitle': 'Sign in to manage your AI agents',
    'auth.signup.subtitle': 'Create your account and deploy your first AI agent',
    'auth.fullname': 'Full Name',
    'auth.company': 'Company Name',
    'auth.role': 'Your Role',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.signin.button': 'Sign In',
    'auth.signup.button': 'Create Account',
    'auth.toggle.signup': "Don't have an account? Sign up",
    'auth.toggle.signin': 'Already have an account? Sign in',
    'auth.back': 'Back to home',
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': "Here's what's happening with your AI agents at",
    'dashboard.stats.total': 'Total Agents',
    'dashboard.stats.active': 'Active Agents',
    'dashboard.stats.conversations': 'Total Conversations',
    'dashboard.stats.response': 'Avg Response Time',
    'dashboard.actions.title': 'Quick Actions',
    'dashboard.actions.create': 'Create New Agent',
    'dashboard.actions.manage': 'Manage Agents',
    'dashboard.actions.analytics': 'View Analytics',
    'dashboard.actions.billing': 'Billing & Subscription',
    'dashboard.recent.title': 'Recent Agents',
    'dashboard.recent.empty': 'No agents created yet',
    'dashboard.recent.cta': 'Create your first agent',
    'nav.overview': 'Overview',
    'nav.agents': 'Manage Agents',
    'nav.analytics': 'Analytics',
    'nav.billing': 'Billing',
    'nav.admin': 'Admin',
    'nav.signout': 'Sign Out',
    'agents.title': 'Manage AI Agents',
    'agents.subtitle': 'View and manage all your deployed agents',
    'agents.create': 'Create New Agent',
    'agents.empty.title': 'No agents yet',
    'agents.empty.subtitle': 'Get started by creating your first AI agent to automate your business processes',
    'agents.empty.cta': 'Create Your First Agent',
    'agents.status.active': 'Active',
    'agents.status.inactive': 'Inactive',
    'agents.action.activate': 'Activate',
    'agents.action.deactivate': 'Deactivate',
    'agents.action.duplicate': 'Duplicate',
    'agents.action.delete': 'Delete',
    'create.title': 'Create New AI Agent',
    'create.subtitle': 'Follow these steps to deploy your AI agent',
    'create.step1': 'Choose Agent Template',
    'create.step2': 'Configure Agent',
    'create.step3': 'Select Channels',
    'create.step4': 'Add Knowledge Base',
    'create.name': 'Agent Name',
    'create.description': 'Description',
    'create.channels.title': 'Choose where your agent will be deployed',
    'create.knowledge.title': 'Add information for your agent to reference',
    'create.knowledge.faq': 'FAQ Title',
    'create.knowledge.answer': 'Answer / Content',
    'create.knowledge.add': 'Add Item',
    'create.knowledge.added': 'Added Items:',
    'create.button.previous': 'Previous',
    'create.button.next': 'Next',
    'create.button.launch': 'Launch Agent',
    'create.button.creating': 'Creating...',
    'analytics.title': 'Analytics & Performance',
    'analytics.subtitle': 'Track your AI agents performance and impact',
    'analytics.conversations': 'Total Conversations',
    'analytics.resolved': 'Resolved Queries',
    'analytics.response': 'Avg Response Time',
    'analytics.revenue': 'Revenue Generated',
    'analytics.breakdown': 'Agent Performance Breakdown',
    'analytics.empty': 'No analytics data available yet',
    'analytics.empty.subtitle': 'Create agents to start tracking performance',
    'billing.title': 'Billing & Subscription',
    'billing.subtitle': 'Manage your subscription and billing information',
    'billing.current': 'Current Plan',
    'billing.current.text': 'You are currently on the',
    'billing.permonth': 'per month',
    'billing.nextbilling': 'Next billing date:',
    'billing.plans': 'Available Plans',
    'billing.plan.current': 'Current Plan',
    'billing.plan.upgrade': 'Upgrade to',
    'billing.invoices': 'Invoice History',
    'billing.invoices.empty': 'No invoices yet',
    'billing.invoices.date': 'Date',
    'billing.invoices.amount': 'Amount',
    'billing.invoices.status': 'Status',
    'billing.invoices.paid': 'Paid',
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Platform overview and management',
    'admin.stats.users': 'Total Users',
    'admin.stats.companies': 'Total Companies',
    'admin.stats.agents': 'Total Agents',
    'admin.stats.subscriptions': 'Active Subscriptions',
    'admin.companies': 'All Companies',
    'admin.companies.empty': 'No companies registered yet',
    'admin.companies.name': 'Company Name',
    'admin.companies.agents': 'Agents',
    'admin.companies.subscription': 'Subscription',
    'admin.companies.created': 'Created',
    'loading': 'Loading...',
    'benefits.support': '24/7 automated support',
    'benefits.cost': 'Reduce operational costs by 70%',
    'benefits.scale': 'Scale instantly without hiring',
    'benefits.multichannel': 'Multi-channel deployment',
    'benefits.training': 'Custom AI training',
    'benefits.analytics': 'Real-time analytics',
    'myagents.title': 'My AI Agents',
    'myagents.subtitle': 'Manage your activated agent instances',
    'myagents.pause': 'Pause',
    'myagents.resume': 'Resume',
    'myagents.archive': 'Archive',
    'myagents.run': 'Run Agent',
    'myagents.usage': 'Usage',
    'myagents.lastused': 'Last Used',
    'myagents.activated': 'Activated',
    'myagents.configuration': 'Configuration',
    'myagents.params': 'params',
    'myagents.executions': 'executions',
    'company.title': 'Company Profile',
    'company.subtitle': 'Manage your company information and settings',
    'company.basic': 'Basic Information',
    'company.billing': 'Billing Information',
    'company.name': 'Company Name',
    'company.country': 'Country',
    'company.selectcountry': 'Select country',
    'company.industry': 'Industry',
    'company.selectindustry': 'Select industry',
    'company.language': 'Language Preference',
    'company.timezone': 'Timezone',
    'company.billingemail': 'Billing Email',
    'company.vat': 'VAT/Tax Number',
    'company.address': 'Billing Address',
    'company.save': 'Save Changes',
    'company.saving': 'Saving...',
    'company.success': 'Company profile updated successfully!',
    'company.error': 'Failed to save company profile',
  },
  ar: {
    'nav.signin': 'تسجيل الدخول',
    'nav.getstarted': 'ابدأ الآن',
    'hero.title': 'عملك، مدعوم بقوة',
    'hero.title.highlight': 'وكلاء الذكاء الاصطناعي',
    'hero.subtitle': 'انشر وكلاء ذكاء اصطناعي أذكياء لأتمتة المبيعات والدعم والتسويق والموارد البشرية والمزيد. وسّع نطاق عملك دون توسيع فريقك.',
    'hero.cta.start': 'ابدأ مجانًا',
    'hero.cta.pricing': 'عرض الأسعار',
    'features.title': 'وكلاء الذكاء الاصطناعي لكل وظيفة تجارية',
    'features.subtitle': 'انشر وكلاء متخصصين يعملون على مدار الساعة لتنمية عملك',
    'feature.support.title': 'دعم العملاء بالذكاء الاصطناعي',
    'feature.support.desc': 'تعامل مع استفسارات العملاء على مدار الساعة بوكلاء ذكاء اصطناعي أذكياء يحلون المشكلات على الفور',
    'feature.sales.title': 'وكيل المبيعات',
    'feature.sales.desc': 'تأهيل العملاء المحتملين وجدولة العروض التوضيحية وإتمام الصفقات تلقائيًا باستخدام أتمتة المبيعات المدعومة بالذكاء الاصطناعي',
    'feature.marketing.title': 'وكيل التسويق',
    'feature.marketing.desc': 'إنشاء الحملات وتحليل الأداء وإشراك العملاء باستخدام الذكاء الاصطناعي التسويقي المعتمد على البيانات',
    'feature.hr.title': 'وكيل الموارد البشرية',
    'feature.hr.desc': 'تبسيط التوظيف والتأهيل واستفسارات الموظفين من خلال أتمتة الموارد البشرية الذكية',
    'feature.accounting.title': 'وكيل المحاسبة',
    'feature.accounting.desc': 'معالجة الفواتير وتتبع النفقات وإنشاء التقارير المالية تلقائيًا',
    'feature.analytics.title': 'وكيل تحليل البيانات',
    'feature.analytics.desc': 'تحليل البيانات وإنشاء الرؤى وإنشاء التصورات باستخدام التحليلات المدعومة بالذكاء الاصطناعي',
    'testimonials.title': 'موثوق به من قبل الشركات المتطلعة',
    'testimonials.subtitle': 'اطلع على ما يقوله عملاؤنا عن وكلاء الذكاء الاصطناعي',
    'cta.title': 'هل أنت مستعد لتحويل عملك؟',
    'cta.subtitle': 'انضم إلى آلاف الشركات التي تستخدم وكلاء الذكاء الاصطناعي لأتمتة عملياتها',
    'cta.button': 'ابدأ تجربتك المجانية',
    'footer.product': 'المنتج',
    'footer.company': 'الشركة',
    'footer.contact': 'اتصل بنا',
    'footer.features': 'الميزات',
    'footer.pricing': 'الأسعار',
    'footer.usecases': 'حالات الاستخدام',
    'footer.about': 'حول',
    'footer.blog': 'المدونة',
    'footer.careers': 'الوظائف',
    'footer.rights': 'جميع الحقوق محفوظة',
    'auth.welcome': 'مرحبًا بعودتك',
    'auth.getstarted': 'ابدأ',
    'auth.signin.subtitle': 'سجل الدخول لإدارة وكلاء الذكاء الاصطناعي الخاصة بك',
    'auth.signup.subtitle': 'أنشئ حسابك وانشر وكيل الذكاء الاصطناعي الأول الخاص بك',
    'auth.fullname': 'الاسم الكامل',
    'auth.company': 'اسم الشركة',
    'auth.role': 'دورك',
    'auth.email': 'عنوان البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.signin.button': 'تسجيل الدخول',
    'auth.signup.button': 'إنشاء حساب',
    'auth.toggle.signup': 'ليس لديك حساب؟ سجل',
    'auth.toggle.signin': 'لديك حساب بالفعل؟ سجل الدخول',
    'auth.back': 'العودة إلى الصفحة الرئيسية',
    'dashboard.welcome': 'مرحبًا بعودتك',
    'dashboard.subtitle': 'إليك ما يحدث مع وكلاء الذكاء الاصطناعي الخاصة بك في',
    'dashboard.stats.total': 'إجمالي الوكلاء',
    'dashboard.stats.active': 'الوكلاء النشطون',
    'dashboard.stats.conversations': 'إجمالي المحادثات',
    'dashboard.stats.response': 'متوسط وقت الاستجابة',
    'dashboard.actions.title': 'إجراءات سريعة',
    'dashboard.actions.create': 'إنشاء وكيل جديد',
    'dashboard.actions.manage': 'إدارة الوكلاء',
    'dashboard.actions.analytics': 'عرض التحليلات',
    'dashboard.actions.billing': 'الفوترة والاشتراك',
    'dashboard.recent.title': 'الوكلاء الأخيرون',
    'dashboard.recent.empty': 'لم يتم إنشاء أي وكلاء بعد',
    'dashboard.recent.cta': 'أنشئ وكيلك الأول',
    'nav.overview': 'نظرة عامة',
    'nav.agents': 'إدارة الوكلاء',
    'nav.analytics': 'التحليلات',
    'nav.billing': 'الفوترة',
    'nav.admin': 'المسؤول',
    'nav.signout': 'تسجيل الخروج',
    'agents.title': 'إدارة وكلاء الذكاء الاصطناعي',
    'agents.subtitle': 'عرض وإدارة جميع الوكلاء المنشورين',
    'agents.create': 'إنشاء وكيل جديد',
    'agents.empty.title': 'لا توجد وكلاء بعد',
    'agents.empty.subtitle': 'ابدأ بإنشاء وكيل الذكاء الاصطناعي الأول الخاص بك لأتمتة عمليات عملك',
    'agents.empty.cta': 'أنشئ وكيلك الأول',
    'agents.status.active': 'نشط',
    'agents.status.inactive': 'غير نشط',
    'agents.action.activate': 'تفعيل',
    'agents.action.deactivate': 'إلغاء التفعيل',
    'agents.action.duplicate': 'نسخ',
    'agents.action.delete': 'حذف',
    'create.title': 'إنشاء وكيل ذكاء اصطناعي جديد',
    'create.subtitle': 'اتبع هذه الخطوات لنشر وكيل الذكاء الاصطناعي الخاص بك',
    'create.step1': 'اختر قالب الوكيل',
    'create.step2': 'تكوين الوكيل',
    'create.step3': 'اختر القنوات',
    'create.step4': 'إضافة قاعدة المعرفة',
    'create.name': 'اسم الوكيل',
    'create.description': 'الوصف',
    'create.channels.title': 'اختر المكان الذي سيتم نشر الوكيل فيه',
    'create.knowledge.title': 'أضف معلومات ليرجع إليها الوكيل',
    'create.knowledge.faq': 'عنوان السؤال',
    'create.knowledge.answer': 'الإجابة / المحتوى',
    'create.knowledge.add': 'إضافة عنصر',
    'create.knowledge.added': 'العناصر المضافة:',
    'create.button.previous': 'السابق',
    'create.button.next': 'التالي',
    'create.button.launch': 'إطلاق الوكيل',
    'create.button.creating': 'جارٍ الإنشاء...',
    'analytics.title': 'التحليلات والأداء',
    'analytics.subtitle': 'تتبع أداء وتأثير وكلاء الذكاء الاصطناعي الخاصة بك',
    'analytics.conversations': 'إجمالي المحادثات',
    'analytics.resolved': 'الاستفسارات المحلولة',
    'analytics.response': 'متوسط وقت الاستجابة',
    'analytics.revenue': 'الإيرادات المحققة',
    'analytics.breakdown': 'تفصيل أداء الوكيل',
    'analytics.empty': 'لا توجد بيانات تحليلية متاحة بعد',
    'analytics.empty.subtitle': 'أنشئ وكلاء لبدء تتبع الأداء',
    'billing.title': 'الفوترة والاشتراك',
    'billing.subtitle': 'إدارة اشتراكك ومعلومات الفوترة',
    'billing.current': 'الخطة الحالية',
    'billing.current.text': 'أنت حاليًا على خطة',
    'billing.permonth': 'شهريًا',
    'billing.nextbilling': 'تاريخ الفوترة التالي:',
    'billing.plans': 'الخطط المتاحة',
    'billing.plan.current': 'الخطة الحالية',
    'billing.plan.upgrade': 'الترقية إلى',
    'billing.invoices': 'سجل الفواتير',
    'billing.invoices.empty': 'لا توجد فواتير بعد',
    'billing.invoices.date': 'التاريخ',
    'billing.invoices.amount': 'المبلغ',
    'billing.invoices.status': 'الحالة',
    'billing.invoices.paid': 'مدفوع',
    'admin.title': 'لوحة المسؤول',
    'admin.subtitle': 'نظرة عامة وإدارة المنصة',
    'admin.stats.users': 'إجمالي المستخدمين',
    'admin.stats.companies': 'إجمالي الشركات',
    'admin.stats.agents': 'إجمالي الوكلاء',
    'admin.stats.subscriptions': 'الاشتراكات النشطة',
    'admin.companies': 'جميع الشركات',
    'admin.companies.empty': 'لم يتم تسجيل أي شركات بعد',
    'admin.companies.name': 'اسم الشركة',
    'admin.companies.agents': 'الوكلاء',
    'admin.companies.subscription': 'الاشتراك',
    'admin.companies.created': 'تاريخ الإنشاء',
    'loading': 'جارٍ التحميل...',
    'benefits.support': 'دعم آلي على مدار الساعة',
    'benefits.cost': 'خفض التكاليف التشغيلية بنسبة 70%',
    'benefits.scale': 'التوسع الفوري دون توظيف',
    'benefits.multichannel': 'النشر متعدد القنوات',
    'benefits.training': 'تدريب مخصص للذكاء الاصطناعي',
    'benefits.analytics': 'تحليلات في الوقت الفعلي',
    'myagents.title': 'وكلائي الذكية',
    'myagents.subtitle': 'إدارة نسخ الوكلاء المفعلة',
    'myagents.pause': 'إيقاف مؤقت',
    'myagents.resume': 'استئناف',
    'myagents.archive': 'أرشفة',
    'myagents.run': 'تشغيل الوكيل',
    'myagents.usage': 'الاستخدام',
    'myagents.lastused': 'آخر استخدام',
    'myagents.activated': 'تم التفعيل',
    'myagents.configuration': 'الإعدادات',
    'myagents.params': 'معامل',
    'myagents.executions': 'تنفيذ',
    'myagents.based': 'بناءً على:',
    'myagents.details': 'تفاصيل النسخة',
    'myagents.status': 'الحالة',
    'myagents.totalexecutions': 'إجمالي التنفيذات',
    'myagents.created': 'تاريخ الإنشاء',
    'myagents.never': 'أبدًا',
    'myagents.notactivated': 'لم يتم التفعيل',
    'company.title': 'ملف الشركة',
    'company.subtitle': 'إدارة معلومات وإعدادات شركتك',
    'company.basic': 'المعلومات الأساسية',
    'company.billing': 'معلومات الفوترة',
    'company.name': 'اسم الشركة',
    'company.country': 'الدولة',
    'company.selectcountry': 'اختر الدولة',
    'company.industry': 'الصناعة',
    'company.selectindustry': 'اختر الصناعة',
    'company.language': 'تفضيل اللغة',
    'company.timezone': 'المنطقة الزمنية',
    'company.billingemail': 'البريد الإلكتروني للفوترة',
    'company.vat': 'رقم الضريبة/VAT',
    'company.address': 'عنوان الفوترة',
    'company.save': 'حفظ التغييرات',
    'company.saving': 'جارٍ الحفظ...',
    'company.success': 'تم تحديث ملف الشركة بنجاح!',
    'company.error': 'فشل حفظ ملف الشركة',
    'onboarding.welcome': '!مرحباً بك، لنقم بإعداد شركتك',
    'onboarding.setup': 'إعدادات الشركة',
    'onboarding.step1': 'أخبرنا عن شركتك للبدء',
    'onboarding.step2': 'ضبط تفضيلات شركتك',
    'onboarding.complete': 'إكمال الإعداد',
    'company.nameplaceholder': 'أدخل اسم شركتك',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'ar')) {
      setLanguageState(savedLang);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
